name: '(Dev) Deploy to Cloud run'

env:
  IMAGE: '${{ vars.GC_REGION }}-docker.pkg.dev/${{ vars.GC_PROJECT_ID }}/${{ vars.GCR_SERVICE_NAME }}/sb-hook:develop'

on: workflow_dispatch

jobs:
  build-and-deploy:
    environment: CI
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - run: echo "pipeline running on ${{ vars.GO_ENV }}"

    - name: 'GCloud Auth'
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: ${{ vars.GC_PROJECT_ID }}
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: 'Configure Docker'
      run: |-
        gcloud auth configure-docker "${{ vars.GC_REGION }}-docker.pkg.dev" --quiet

    - name: 'Build image'
      run: 'docker build -t ${{ env.IMAGE }} .'

    - name: 'Push image'
      run: 'docker push ${{ env.IMAGE }}'

    - name: 'GCloud Deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: ${{ vars.GCR_SERVICE_NAME }}
        image: '${{ env.IMAGE }}'
        region: ${{ vars.GC_REGION }}
        env_vars: |-
          GO_ENV=development
          OMISE_API_KEY=${{ secrets.OMISE_API_KEY }}
          OMISE_SECRET_KEY=${{ secrets.OMISE_SECRET_KEY }}