name: '(Dev) Game test ci-cd'

on: workflow_dispatch

jobs:
  development-deploy:
    runs-on: 'ubuntu-latest'
    if: ${{ github.ref_name == 'develop' }}

    steps:
    - uses: 'actions/checkout@v4'

    - run: echo "Deploying $GITHUB_REF_NAME"

  else-deploy:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: 'actions/checkout@v4'

    - run: echo "Deploying on $GITHUB_REF_NAME"
